apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}-auth-deploy
  namespace: ${NAMESPACE_NAME}
  labels:
    app: ${SERVICE_NAME}-auth
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${SERVICE_NAME}-auth
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}-auth
    spec:
      containers:
      - name: ${SERVICE_NAME}-auth-microservice
        image: ${IMAGE_NAME}-auth
        ports:
